### ISSUE TITLE
Improper json leads to status 400

### ISSUE THREAD

**Issue by elmalto** [leanovate/play-mockws#10]
Hi I have a couple of POST requests where the receiving server demands a non-standard JSON format. Unfortunately MockWS on 2.4 immediately returns status 400 with

```
For request 'POST https://mockserver.com/mockpost' [Invalid Json: Unexpected character (&#x27;,&#x27; (code 44)): expected a valid value (number, String, array, object, &#x27;true&#x27;, &#x27;false&#x27; or &#x27;null&#x27;)
 at [Source: [B@2c070ac1; line: 1, column: 3]]
```

I just upgraded from 2.3 to 2.4. Going back to 2.3 solves the issue

**Comment by yanns** [comment]
Can you please try with the last version?

**Comment by yanns** [comment]
I guess this issue is fixed now.
I close it.
Please fell free to open it again.
