### ISSUE TITLE
Release 2.8.0 or 2.8.1?

### ISSUE THREAD

**Issue by dgoetsch** [leanovate/play-mockws#104]
Please release a new version of play-mockws to support the latest minor akka version.

**Comment by avdv** [comment]
If you are only concerned about the Akka version, 2.6 is compatible to 2.5... So everything should just work if you ensure that you upgrade *all* of your Akka modules to the same version.

**Comment by dgoetsch** [comment]
It is not compatible.  There is a specific breaking integration with this library.

The `MockWs` class requires an `ActorMaterializer` in its constructor - but `ActorMaterializer` was deprecated.  In our code, I can change all instances of ActorMaterializer to `Materializer`, except for those passed to MockWs. https://github.com/leanovate/play-mockws/blob/master/src/main/scala/mockws/MockWS.scala#L68

The code in this library has already been updated.  I tested it by cloning and building locally; all that needs to happen is the release needs to be cut and put in the correct place.

**Comment by yanns** [comment]
@avdv do you want to take care of the release or should I?

**Comment by avdv** [comment]
> It is not compatible. There is a specific breaking integration with this library.

@dgoetsch I was talking about binary compatibility. If you're programming against 2.6, you cannot expect that interface from libraries programmed against 2.5. So you would have to use deprecated APIs.

> do you want to take care of the release or should  I?

@yanns How? I could push the release button, but it seems I won't be able to push out the release to maven central... Or, can I?

**Comment by yanns** [comment]
@avdv please open a ticket on https://issues.sonatype.org to that they add your ssh key as allowed to publish those artifacts. And give me the ticket number so that I can confirm.

**Comment by avdv** [comment]
@yanns I have opened ticket OSSRH-55040

**Comment by avdv** [comment]
The 2.8.0 release is out!

**Comment by yanns** [comment]
thx @avdv 🏆

**Comment by yanns** [comment]
@avdv congrats!
Maybe you can add the `2.8.0` to https://github.com/leanovate/play-mockws#adding-play-mockws-to-your-project ?

**Comment by avdv** [comment]
> Maybe you can add the `2.8.0` to [leanovate/play-mockws#adding-play-mockws-to-your-project](https://github.com/leanovate/play-mockws#adding-play-mockws-to-your-project) ?

Right, forgot about that!

**Comment by dgoetsch** [comment]
Thank you!
