### ISSUE TITLE
Limited support for authentication header/withAuthentication

### ISSUE THREAD

**Issue by cgbaker** [leanovate/play-mockws#12]
Regarding MockWS 2.3.x: 

MockWS's mocked request holder discards authentication credentials passed in to withAuth. 
This means that the routed action can't look at the FakeRequest to get them; neither can it get access to the mocked RequestHolder from the FakeRequest in order to determine whether withAuth was even called. (I would have to do the test after the handler is constructed but before executing it.) 

FakeAuth doesn't support withAuth, so an explicit header would have to be appropriately constructed and passed in along with the existing headers. I imagine this could be a hassle, but adding support for Basic Authentication should be fairly straightforward.

Thoughts? If this is something that is reasonable, I can submit a patch.

**Comment by yanns** [comment]
Yes we could simply copy/paste the code from the NingWS implementation: https://github.com/playframework/playframework/blob/cde65d987b6cf3c307dfab8269b87a65c5e84575/framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala#L104

an construct the http header ourselves.

Actually, we could maybe extract the `withSign` implementation into another class that could be also used by the NingWS. It would require to patch the playframework though, but would lead to less redundancy.

**Comment by Manc** [comment]
I'd welcome support for `withAuth` too. I was genuinely willing to contribute, but I'm still fairly new to all this and have to declare myself defeated for now. I can't figure out how add the headers to the FakeRequest properly.

So all I could do is write a [test](https://github.com/leanovate/play-mockws/compare/master...Manc:add-auth-support#diff-01f7872915dd4eb7b11db533f5f2baf0R266), which currently fails of course.

**Comment by yanns** [comment]
@Manc thx for your test. Based on it, I could write a minimal implementation.
Feel free to apply it to your branch and to provide a pull request once you are satisfied with the result.

Diff:
```
diff --git a/src/main/scala/mockws/FakeWSRequestHolder.scala b/src/main/scala/mockws/FakeWSRequestHolder.scala
index a20eae5..045ab8b 100644
--- a/src/main/scala/mockws/FakeWSRequestHolder.scala
+++ b/src/main/scala/mockws/FakeWSRequestHolder.scala
@@ -1,6 +1,7 @@
 package mockws

 import java.net.URLEncoder
+import java.util.Base64

 import akka.stream.ActorMaterializer
 import akka.stream.scaladsl.{FileIO, Sink, Source}
@@ -112,10 +113,23 @@ case class FakeWSRequestHolder(
     // Real WSClients will actually interrupt the response Enumerator while it's streaming.
     // I don't want to go down that rabbit hole. This is close enough for most cases.
     applyRequestTimeout(fakeRequest) {
-      action(fakeRequest).run(requestBodyEnumerator)
+      action(sign(fakeRequest)).run(requestBodyEnumerator)
     }
   }

+  private def sign(req: FakeRequest[_]): FakeRequest[_] = auth match {
+    case None ⇒ req
+    case Some((username, password, WSAuthScheme.BASIC)) ⇒
+      val encoded = new String(
+        Base64.getMimeEncoder().encode(s"$username:$password".getBytes("UTF-8")), "UTF-8")
+      req.withHeaders("Authorization" → s"Basic: $encoded")
+    case Some((_, _, unsupported)) ⇒ throw new Exception(
+      s"""do not support auth method $unsupported.
+         |Help us to provide support for this.
+         |Send us a test at https://github.com/leanovate/play-mockws/issues
+       """.stripMargin)
+  }
+
   private def applyRequestTimeout[T](req: FakeRequest[_])(future: Future[T]) = requestTimeout match {
     case Some(delay) => timeoutProvider.timeout(
       future = future,
diff --git a/src/test/scala/mockws/MockWSTest.scala b/src/test/scala/mockws/MockWSTest.scala
index 149bd67..f3f2bc7 100644
--- a/src/test/scala/mockws/MockWSTest.scala
+++ b/src/test/scala/mockws/MockWSTest.scala
@@ -273,7 +273,7 @@ class MockWSTest extends FunSuite with Matchers with PropertyChecks {
       }
     }

-    val wsResponse = await(ws.url("/").withAuth("foo", "myPas$worD", WSAuthScheme.BASIC).get)
+    val wsResponse = await(ws.url("/").withAuth("foo", "Pas$worD", WSAuthScheme.BASIC).get)
     wsResponse.status shouldEqual OK
     ws.close()
   }
```

**Comment by yanns** [comment]
Nobody motivated for submitting a pull request?
There is one test and one suggestion of implementation.
It is the perfect opportunity to contribute to open source! 😉 ❤️

**Comment by Manc** [comment]
@yanns Many thanks for your replies and sorry I didn't reply earlier. I'll try as soon as I get the chance, hopefully this week.

**Comment by avdv** [comment]
@Manc ping. Any progress on a PR?
