### ISSUE TITLE
Support for cookies on request?

### ISSUE THREAD

**Issue by gregsilin** [leanovate/play-mockws#14]
Hi,

Currently, there doesn't seem to be a way to inject cookies into the mock request when using the mockws library.  What's the feasibility of adding this functionality?

**Comment by yanns** [comment]
Can you explain why it is not possible?
Sending the cookie from the client is simply sending an header.
And adding a cookie from the client is also simply sending an header.

**Comment by gregsilin** [comment]
Duh, I knew that :). thanks
