### ISSUE TITLE
useable outside of play applications?

### ISSUE THREAD

**Issue by Ir1sh** [leanovate/play-mockws#20]
plays WS client can be used as a stand alone client outside of a play app.  Can / should this mock also be used in that situation?

I am trying it where the project definition looks like 

```lazy val `blah` = (project in file("preference-service-client"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.0.1" % "test",
      "com.typesafe.play" %% "play-ws" % "2.5.12",
      "de.leanovate.play-mockws" %% "play-mockws" % "2.5.1" % "test"
    ),
    version := "1.0.0",
    scalaVersion := "2.11.8",
    scalafmtConfig := Some(file(".scalafmt")),
    reformatOnCompileSettings
  )
  .dependsOn(root)```

and root is a full blown play app

however when execute is called on the ws request I get a class not found exception on this line

https://github.com/leanovate/play-mockws/blob/master/src/main/scala/mockws/FakeWSRequestHolder.scala#L111

the stack trace is as follows:

```
com.yadda *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: play/api/test/FakeRequest$
[info]   at mockws.FakeWSRequestHolder.fakeRequest$1(FakeWSRequestHolder.scala:111)
[info]   at mockws.FakeWSRequestHolder.executeResult(FakeWSRequestHolder.scala:115)
[info]   at mockws.FakeWSRequestHolder.execute(FakeWSRequestHolder.scala:87)
[info]   at com.iofficecorp.preferences.PreferenceClient$.get(PreferencesClient.scala:37)
[info]   at com.yadda$$anonfun$2.apply(PreferenceClientSpec.scala:92)
[info]   at com.yadda$$anonfun$2.apply(PreferenceClientSpec.scala:90)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: play.api.test.FakeRequest$
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at mockws.FakeWSRequestHolder.fakeRequest$1(FakeWSRequestHolder.scala:111)
[info]   at mockws.FakeWSRequestHolder.executeResult(FakeWSRequestHolder.scala:115)
[info]   at mockws.FakeWSRequestHolder.execute(FakeWSRequestHolder.scala:87)
[info]   at com.yada$.get(PreferencesClient.scala:37)
```

I am guessing this is because wsMock expects an implementation of FakeRequest to be injected by play and therefore this makes wsMock not usable outside of a play app but I Want to make sure I am not missing something

**Comment by yanns** [comment]
play-mockws was created when the WS client was integrated into play.
For the moment, it can only be used with a play application.

It may be a good move to support the new standalone WS client.

**Comment by Ir1sh** [comment]
Thanks for the fast reply, might you be able to point me in the right direction to how to do that and I might be able to spend the time to make it happen?

**Comment by Ir1sh** [comment]
from my brief look through the code base here are the things may need to be factored out, correct me if I am wrong:

TimeoutProvider.scala -> play.core.NamedThreadFactory
Route.Scala and MockWS -> play.api.mvc.EssentialAction
FakeWSRequestHolder.scala -> play.api.libs.iteratee.Enumerator & play.api.libs.streams.Streams

play.api.libs.ws.{WSClient, WSRequest} should still be provided by the library??

Not sure exactly how to tell what would or wont be added to the project when you depend on the play-ws itself but from a quick look at https://github.com/playframework/play-ws/blob/master/project/Dependencies.scala seems liek its just play-json

**Comment by yanns** [comment]
The core functionality is using play to resolve requests/responses: https://github.com/leanovate/play-mockws/blob/master/src/main/scala/mockws/FakeWSRequestHolder.scala#L110

Maybe the better way is to add play as test dependency?

**Comment by yanns** [comment]
I close this issue for now. Not depending on play is not an option for now.

**Comment by francisdb** [comment]
@yanns adding play as dependency is not enough as MockWS extends `WSClient` but not `StandaloneWSClient`
Could you make that change?

As workaround this wrapper can be used

```scala
// TODO remove once this is fixed: https://github.com/leanovate/play-mockws/issues/20
object StandaloneMockWs{
  def apply(mockWs: MockWS) = new StandaloneMockWs(mockWs)
}
class StandaloneMockWs(mockWs: MockWS) extends StandaloneWSClient{
  override def underlying[T]: T = mockWs.underlying[T]

  override def url(url: String): StandaloneWSRequest = mockWs.url(url)

  override def close(): Unit = mockWs.close()
}
```

**Comment by francisdb** [comment]
And one more annoyance is that `FakeWSRequestHolder` depends on `AhcWSResponse`, which makes depending on `play-ws` not enough, I need to add a test dependency to `play-ahc-ws`
