### ISSUE TITLE
create version for play 2.6.0-M1 + scala v 2.12.1

### ISSUE THREAD

**Issue by domdorn** [leanovate/play-mockws#21]

**Comment by domdorn** [comment]
I started with the migration.. got the code to compile again (except for the consumers in the test class)
please have a look
https://github.com/domdorn/play-mockws/tree/2.6.x

tests are still mostly failing.

**Comment by domdorn** [comment]
https://github.com/leanovate/play-mockws/pull/22

**Comment by yanns** [comment]
https://github.com/leanovate/play-mockws/releases/tag/v2.6.0-M1
