### ISSUE TITLE
Possible to "spy" on a request's body

### ISSUE THREAD

**Issue by jnd-noggin** [leanovate/play-mockws#24]
Hello.
First I would like to say this library has been a great help. Thanks.

I have this use case, where my code is calling a REST API. With the library, I can mock the response and check it has indeed been called. In addition, I would like to intercept the request's body, and make sure it contains the right data. What would be the best way to do this (if it's even possible) ?

**Comment by yanns** [comment]
You could introduce a mutable state in your test, update it in the mock rock, and check it afterwards.
Pseudo-code
```
"my test" {
    val body = new AtomicReference[Option[String]](None)
    val ws = MockWS {
      case (POST, "/post")     => Action { request ⇒
        body.set(request.body.asText)
        Ok("post ok")
      }
    }
    
    await(ws.url("/post").withMethod("POST").withBody("hello").execute()).body     shouldEqual "post ok"
    body.get() shouldEqual Some("hello")
    ws.close()
}
```

**Comment by jnd-noggin** [comment]
Great. Thanks a lot !
