### ISSUE TITLE
MockWS with dynamic url

### ISSUE THREAD

**Issue by tanyagorn** [leanovate/play-mockws#249]
I want to parse dynamic url into case url of MockWS like this

```
    val ws = MockWS {
      case ("POST", mockServer.getUrl + "/predict-nationality") =>
        Action {
          Ok(Json.obj(
            "ARE" -> 0.0015790796301290394,
            "ARG" -> 0.0015750796301290393,
            "AUS" -> 0.027795471251010895
          ))
        }
    }
```

However, I got error saying that **stable identifier required**. Only String without any modification is accepted there. But I really need to use **mockServer.getUrl + "/predict-nationality"** as url in this case. I also can't define it as val because of the MockWS {} scope.

How can I deal with this? any other ways to use MockWS with dynamic url?

**Comment by gaeljw** [comment]
@tanyagorn Does the following works?

```scala
 val ws = MockWS {
     val url = mockServer.getUrl + "/predict-nationality"
     val routes: Routes = {
       case ("POST", `url`) =>
        Action {
          Ok(Json.obj(
            "ARE" -> 0.0015790796301290394,
            "ARG" -> 0.0015750796301290393,
            "AUS" -> 0.027795471251010895
          ))
        }
    }
    routes
}
```

**Comment by gaeljw** [comment]
I'll close the issue as there hasn't been any discussion for more than a year. Feel free to reopen if needed.
