### ISSUE TITLE
when no route defined return Future.failed(Exception)

### ISSUE THREAD

**Issue by Ir1sh** [leanovate/play-mockws#25]
The default implementation of play-ws when called against a host it cannot resolve returns a Failure(UnknownHostException).

What do you think of this line https://github.com/leanovate/play-mockws/blob/c15d898d238e3c429a1955bb26e826bb27b241ac/src/main/scala/mockws/FakeWSRequestHolder.scala#L105 returning the same instead of throwing an exception?  It could even just return that exception in a failed future if you didnt want to return an UnknownHostException specifically.

I think this would make testing some specific failure cases easier, right now I am left with creating a real instance and passing in bad urls, obviously I lose the nice route test sugar play-mockws provides doing things this way

**Comment by yanns** [comment]
it's a good idea. A `Future.failed()` would be much better.
Do you want to contribute a patch for this?

**Comment by Ir1sh** [comment]
great, yeah will do in the next couple days hopefully

**Comment by Ir1sh** [comment]
forgot about this but this week fo sho

**Comment by sahilahmadlone** [comment]
@yanns Can you look at this https://github.com/leanovate/play-mockws/pull/35

**Comment by yanns** [comment]
fixed by https://github.com/leanovate/play-mockws/pull/35
Will be released in 2.6.6
