### ISSUE TITLE
Still maintained

### ISSUE THREAD

**Issue by Dichotomia** [leanovate/play-mockws#268]
Hello,

More than one year without commits.

Is this project still maintained?

Best Regards

**Comment by BillOTei** [comment]
as Play Framework is now maintained by the community and still in 2.8.x release, my guess is that there is no need for many developments atm.

**Comment by Dichotomia** [comment]
Hello. Have you checked with Play 2.9.X. The release is coming soon.

**Comment by Dichotomia** [comment]
The release is here

**Comment by avdv** [comment]
Hi.

I cannot speak for @yanns, but my interest / area of work has changed quite a bit, so this project is in (very) low maintenance mode...

I can put aside some time to work on some issues / review PRs sometimes. But don't hold your breath.

**Comment by yanns** [comment]
Hi, same for me.

If some people are motivated to take over, that'd be great (https://github.com/leanovate/play-mockws/issues/66)

**Comment by gaeljw** [comment]
@yanns @avdv I'd be happy to help keep this project up. Let me know how we could make this happen. I'm available on Play's Discord for instance.

**Comment by yanns** [comment]
@gaeljw great to hear! I've added you as maintainer.
My suggestion: in a few weeks (ping me if I forget), I'll check again your contributions and give me more permissions at that time.

**Comment by gaeljw** [comment]
Thanks @yanns 

I don't think there'll be many contributions in the coming weeks. PRs for Play 2.9 and 3.0 are already opened and merged for one of them. I'll review the open one.

What I can help with in the coming weeks is cutting a release and/or making it automated with Github Actions somehow if that's not the case already.

**Comment by yanns** [comment]
Automating release would be great!
I have great experience with [`sbt-ci-release`](https://github.com/sbt/sbt-ci-release)
Ex: https://github.com/sangria-graphql/sangria-federated/commit/cda24f750498234d4da14f79c9120823c4076603

**Comment by gaeljw** [comment]
Okay, I'll open a dedicated issue/PR to discuss this and provide something. Never used sbt-ci-release but I did use sbt-release, sbt-sonatype and co to do the same manually, it should be easier :)

**Comment by avdv** [comment]
I have just manually published release 2.9.0 to sonatype (couldn't get `sonatypeBundleRelease` to work automatically). So, yes sbt-ci-release would be nice, I guess.

Thank you for stepping in @gaeljw !

**Comment by gaeljw** [comment]
I'll close this issue, the project is still active as you can see with latest releases :)

**Comment by yanns** [comment]
@gaeljw Thanks again for your contributions!
I've made you admin of this repository to make sure you have enough rights.
