### ISSUE TITLE
Play 2.6 tests use deprecated Action

### ISSUE THREAD

**Issue by 1gnition** [leanovate/play-mockws#27]
When cloning and running `sbt test` there are a lot of the following warnings:

```
object Action in package mvc is deprecated (since 2.6.0): Inject an ActionBuilder (e.g. DefaultActionBuilder) or extend BaseController/AbstractController/InjectedController
[warn]       case ("PATCH", "/patch") => Action { Ok("patch ok") }
```

**Comment by yanns** [comment]
Do you have any solution for this?

**Comment by 1gnition** [comment]
Yeah, you should inject `DefaultActionBuilder` and do a
```
defaultActionBuilder { request => ... }
```

instead of `Action { request => ... }`

**Comment by yanns** [comment]
Thx for the pointer!

Can you make a PR with one example to see if it's something we can generalize?

**Comment by 1gnition** [comment]
Yeah, I'll try to in the evening

**Comment by 1gnition** [comment]
Hi,

See pull request
https://github.com/leanovate/play-mockws/pull/28
