### ISSUE TITLE
Consider providing a module for each Play version

### ISSUE THREAD

**Issue by gaeljw** [leanovate/play-mockws#329]
Currently the project versioning follows the versioning of Play: play-mockws 2.x is compatible with play 2.x.

I'm not yet familiar with the codebase but it could be interesting to provide one module (one published JAR in the end) for each version of Play and decorrelate the versioning of play-mockws of the one of Play: we'd have play-mockws-2-8, play-mockws-2-9, play-mockws-3-0 with all the same version x.y.z.

This would allow us to release play-mockws with potential bugfixes or just upgrades of our dependencies more easily I believe.

Any opinion on this?

If we do it, I suggest we support play 2.8, 2.9 and 3.0 only as a start. Other versions of Play are too old IMHO.

**Comment by yanns** [comment]
That's a good idea. It'd be easier to manage than different branches.
