### ISSUE TITLE
Real HTTP request is fired

### ISSUE THREAD

**Issue by vojtechsoban** [leanovate/play-mockws#41]
Hi, I'm using MockWS in combination with [WithServer](https://www.playframework.com/documentation/2.6.x/ScalaFunctionalTestingWithSpecs2#withserver) where MockWS is used for mocking external service and `play.api.libs.ws.ahc.StandaloneAhcWSClient` is used in test to call our endpoint. It worked well before we upgrade to Play 2.6.15 and MockWS 2.6.2. After upgrade it is calling real service which should be mocked. I debugged that when I comment setting `Content-type` mocking works well again but I can't comment it permanently since it is application code to call another service.

```
// application code for calling another service, this is not test code
val wsRequest = ws
      .url(url)
      .withQueryStringParameters(queryParams.toList: _*)
      .withHttpHeaders(
        "Accept" -> "application/json",
        "Content-type" -> "application/json",
        "Authorization" -> "xxxxx",
        "Api-Version" -> "1.1",
        "Cobrand-Name" -> cobrandName
      )
```

Is there some clash with `StandaloneAhcWSClient` or a bug in MockWS?

**Comment by yanns** [comment]
Oh, this is the first time I heard of this, and this is a serious issue.
I don't really know (yet) why you can observe that.

Just to be sure, your `ws` value is pointing to an instance of `MockWS` during the tests, isn't it?

**Comment by vojtechsoban** [comment]
This issue is actually #40, fortunatelly BadRequest comes from MockWS and not from the real server.
