### ISSUE TITLE
Please release 2.5.2

### ISSUE THREAD

**Issue by viggan** [leanovate/play-mockws#58]
Hi,

Can you please release and publish 2.5.2. I need it for multipart support which was added in play 2.5.1, (mockws 2.5.1 is compiled against 2.5.0).
The play version is already bumped in you 2.5 branch.

Thanks a bunch!

**Comment by yanns** [comment]
@viggan the last version in the `play_2.5` branch is ok for you: https://github.com/leanovate/play-mockws/commits/play_2.5 ? I can release this as it is now?

**Comment by viggan** [comment]
Yes! Thank you

**Comment by yanns** [comment]
https://github.com/leanovate/play-mockws/releases/tag/v2.5.2

Actually you know that you can override the play version in your project?
I don't think this release was totally necessary.

**Comment by viggan** [comment]
I know, and i actually am overriding it, problem is that `FakeWSRequestHolder` is extending play class `WSRequest`. And since mockws 2.5.1 is compiled against play 2.5.0 where `WSRequest` did not have the `def post(body: Source[MultipartFormData.Part[Source[ByteString, _]], _]): Future[WSResponse]`  it throws a AbstractMethodError. 
(At least this is what i strongly believe, haven't been able to confirm due to various reasons.)
Thanks a lot for such quick action! When will this get published to mavencentral?

**Comment by yanns** [comment]
It's already on mavencentral: https://repo1.maven.org/maven2/de/leanovate/play-mockws/play-mockws_2.11/2.5.2/
