### ISSUE TITLE
Gzipped responses not working

### ISSUE THREAD

**Issue by elmalto** [leanovate/play-mockws#6]
Sometimes I need to gunzip WS responses and I would like to test this.

However, if I use the following response:

```
val input = new ByteArrayInputStream("my response".getBytes)
val output = new ByteArrayOutputStream()
sbt.IO.gzip(input,output)
Ok(output.toByteArray)
```

and then on the receiving end use
```
scala.io.Source.fromInputStream(new GZIPInputStream(result.underlying[Response].getResponseBodyAsStream)).mkString
```

it throws an `java.util.zip.ZipException: Not in GZIP format` error

edit: changed implementation to underlying, still same issue

**Comment by yanns** [comment]
Thanks for the reporting.
Fix in master: https://github.com/leanovate/play-mockws/commit/b4962ba70c92d038c145adf4e25059de93a3f159
Will be release in the version 0.15

**Comment by yanns** [comment]
version 0.15 is released.
It should land on maven central today.
