### ISSUE TITLE
avoid single point of failure

### ISSUE THREAD

**Issue by yanns** [leanovate/play-mockws#66]
I'm for the moment the only person that:
- can merge a pull request
- perform a release

This kind of situation is dangerous for any project.

I'm opening this issue so that we can fix this situation.

The first step would be to have more people with rights to merge.
They could also help reviewing.

The second step would be to allow more than one person to perform a release.

**Comment by yanns** [comment]
@avdv You are quite active on the project (thx by the way)

Would you be interested in having more rights and reviewing / merging pull requests?

**Comment by avdv** [comment]
> @avdv You are quite active on the project (thx by the way)
> 
> Would you be interested in having more rights and reviewing / merging pull requests?

Hi @yanns, I feel quite honored that you ask me... :blush: But yes, I'd be willing to take a bit of the maintenance burden from you.

**Comment by yanns** [comment]
> But yes, I'd be willing to take a bit of the maintenance burden from you.

Great to hear that!!
I've invited you to the repo.

If someone else is interested, please propose yourself.

My first goal is not to delegate everything 😉  but to be sure that someone else can take care of this project in any case.

**Comment by avdv** [comment]
Since I did successfully pushed out a release we can consider this issue solved, right? :smile:

**Comment by yanns** [comment]
yes, thank you a lot.
It feels good not to be a single point of failure anymore.

**Comment by yanns** [comment]
I wrote something about this: https://yanns.github.io/blog/2020/02/11/open-source-and-sole-maintainers/
@avdv as you're mentioned, do you want me to change something? Remove you? Change the link?

**Comment by avdv** [comment]
Hi Yann,

a nice read! I wouldn't change anything.

Also, I didn't know sangria is still under active development! Thought it was unmaintained.
