### ISSUE TITLE
consider auto-formatting of source files

### ISSUE THREAD

**Issue by yanns** [leanovate/play-mockws#68]
Ex: integrate https://scalameta.org/scalafmt/

could fix https://github.com/leanovate/play-mockws/issues/67

**Comment by brbrown25** [comment]
@yanns I can help if you'd like!

**Comment by yanns** [comment]
@brbrown25 that would be awesome! Thx for proposing.

**Comment by yanns** [comment]
Fixed by https://github.com/leanovate/play-mockws/pull/69
