### ISSUE TITLE
Mock WSRequest is not fully supported

### ISSUE THREAD

**Issue by cui-liqiang** [leanovate/play-mockws#8]
In MockWS.scala, the return value of method url is a mock WSRequest, but there are only 16 methods get defined, while actually there are more than 30 methods defined in WSRequest traits.

I called the "withBody" method, and it failed in the test, as "withBody" method is not mocked and it will return null...

Should it be a fake WSRequest instead of mock one?

**Comment by yanns** [comment]
@cui-liqiang you're right, not al methods are mocked.
Some people send some pull requests to add missing method.
If you want to, you can try to contribute.

**Comment by yanns** [comment]
Implementing `WSRequest` instead of using a mock would ensure that we do not forget any methods.
It is a good idea, but quite a rewrite of the actual code.

**Comment by htmldoug** [comment]
> It is a good idea, but quite a rewrite of the actual code.

Mostly done. I've replaced mockito with a fake concrete implementation [here](https://github.com/htmldoug/play-mockws/commit/a78d484753e2fd9f43f7af3287ef2e733bfcac62) with all tests passing.

@yanns, would you be interested in a PR against 2.3.x after I address the remaining TODOs and add a bit more test coverage?

**Comment by yanns** [comment]
@htmldoug Awesome! Yes, I'd very interesting, thx!!

**Comment by yanns** [comment]
fixed by https://github.com/leanovate/play-mockws/pull/11
